be test

diff --git a/.github/workflows/CICD_BE.yml b/.github/workflows/CICD_BE.yml
--- a/.github/workflows/CICD_BE.yml
+++ b/.github/workflows/CICD_BE.yml
@@ -45,14 +45,14 @@ jobs:
       - name: Build with Maven
         run: mvn clean package -DskipTests
 
-      # - name: Test
-      #   run: mvn test -Dtest=com.chien.bookWorld.*Tests
+      - name: Test
+        run: mvn test -Dtest=com.chien.bookWorld.*Tests
 
-      # - name: Publish Test Report
-      #   uses: mikepenz/action-junit-report@v4
-      #   if: success() || failure() # always run even if the previous step fails 1
-      #   with:
-      #     report_paths: '**/TEST-*.xml'    
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails 1
+        with:
+          report_paths: '**/TEST-*.xml'    
 
       - name: Heroku Install
         env:
