be test

diff --git a/.github/workflows/CICD_BE.yml b/.github/workflows/CICD_BE.yml
--- a/.github/workflows/CICD_BE.yml
+++ b/.github/workflows/CICD_BE.yml
@@ -45,6 +45,15 @@ jobs:
       - name: Build with Maven
         run: mvn clean package -DskipTests  
 
+      - name: Test
+        run: mvn test -Dtest=com.chien.bookWorld.*Tests
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/TEST-*.xml'  
+
       - name: Heroku Install
         env:
           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
@@ -55,15 +64,6 @@ jobs:
           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
         run:
           heroku deploy:jar target/*.jar --app book-world
-
-      - name: Test
-        run: mvn test -Dtest=com.chien.bookWorld.*Tests
-
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/TEST-*.xml'  
 
       # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive1
       # - name: Update dependency graph1 
